#!/usr/bin/env python3
"""Generates docs/passkit-crypto-db.md from tests/verification/passkit_features.rin.
Run:  python3 tools/gen_features_doc.py"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "tests/verification/passkit_features.rin").read_text(encoding="utf-8")
rows, section = [], ""
for line in src.split("\n"):
    m = re.match(r"// =+ (.+?) =+$", line)
    if m:
        section = m.group(1)
        continue
    m = re.match(r'feat\("(F\d{3})", "([^"]*)", ', line)
    if m:
        rows.append((section, m.group(1), m.group(2)))
out = ["# Passkit feature catalog: encryption, databases and container linking", "",
       f"{len(rows)} features. Every row is a check in `tests/verification/passkit_features.rin` that runs on the real interpreter.",
       "Generated by `tools/gen_features_doc.py` — do not edit by hand.", ""]
cur = None
for sec, fid, title in rows:
    if sec != cur:
        cur = sec
        out += ["", f"## {sec}", "", "| ID | Feature |", "|---|---|"]
    out.append(f"| {fid} | {title.replace('|', chr(92) + '|')} |")
(root / "docs/passkit-crypto-db.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print("features:", len(rows))
